#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

LingMaxDns="/etc/LingMaxDns_linux_arm"

start_service() {
 procd_open_instance
 procd_set_param command "$LingMaxDns"
 procd_set_param respawn
 procd_close_instance
}

stop_service() {
rm -f /var/run/LingMaxDns_linux_arm.pid
}

restart() {
stop
start
}
