#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99

USE_PROCD=1
PROG=/etc/LingMaxDns_linux_arm

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" 
	procd_set_param respawn 0
	procd_close_instance
}

stop_service(){
	service_stop "$PROG"
}
